### ISSUE TITLE
Create collapsible sections

### ISSUE THREAD

**Issue by tendermario** [Perfect5th/work-in-progress#1]
Like here: https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f

A collapsible section would help with our organization of notes.

Instead of that example, using something like a class `.collapsible` and some JS could work as well.

**Comment by Perfect5th** [comment]
5d755b65a376bc84b99fe0fc1b5adb235eeb5494 adds support for inline HTML-style collapsible sections in the markdown.

    <details>
      <summary>CLICK HERE</summary>
      Whatever markdown content you want, maybe.
    </details>
